import jsPDF from 'jspdf';
import PptxGenJS from 'pptxgenjs';

/**
 * Export message or document content as a sleek PDF file
 */
export function exportToPDF(title: string, content: string) {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const maxLineWidth = pageWidth - margin * 2;

    // Header Background Accent
    doc.setFillColor(10, 25, 47); // WASO Dark Blue
    doc.rect(0, 0, pageWidth, 25, 'F');

    // WASO Brand Title
    doc.setTextColor(0, 180, 216); // Cyan
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('WASO AI ARCHITECTURE REPORT', margin, 12);

    doc.setTextColor(200, 220, 240);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Created by Wasin • Generated: ${new Date().toLocaleString()}`, margin, 18);

    // Document Title
    doc.setTextColor(15, 23, 42); // Dark slate
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    let currentY = 35;
    doc.text(title.slice(0, 70), margin, currentY);

    currentY += 8;
    doc.setDrawColor(0, 180, 216);
    doc.setLineWidth(0.5);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    currentY += 8;

    // Parse and print text lines
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 41, 59);

    const cleanText = content.replace(/\r\n/g, '\n');
    const lines = doc.splitTextToSize(cleanText, maxLineWidth);

    for (let i = 0; i < lines.length; i++) {
      if (currentY > pageHeight - 20) {
        doc.addPage();
        currentY = 20;

        // Header line on subpages
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.2);
        doc.line(margin, 12, pageWidth - margin, 12);
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text('WASO AI • Polyglot Engineering Document', margin, 10);
        doc.setFontSize(10);
        doc.setTextColor(30, 41, 59);
      }

      const line = lines[i];

      // Format headers or code blocks
      if (line.startsWith('#')) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 120, 180);
        doc.text(line.replace(/^#+\s*/, ''), margin, currentY);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30, 41, 59);
      } else if (line.startsWith('```')) {
        doc.setFont('courier', 'bold');
        doc.setTextColor(147, 51, 234);
        doc.text(line, margin, currentY);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30, 41, 59);
      } else {
        doc.text(line, margin, currentY);
      }

      currentY += 5.5;
    }

    // Save File
    const filename = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 30)}_WASO.pdf`;
    doc.save(filename);
  } catch (err) {
    console.error('Failed to export PDF:', err);
    alert('PDF Export failed. Please try again.');
  }
}

/**
 * Export message or presentation content as a PPTX slide deck
 */
export function exportToPPTX(title: string, content: string) {
  try {
    const pptx = new PptxGenJS();

    pptx.layout = 'LAYOUT_169';
    pptx.author = 'WASO AI (Wasin)';
    pptx.company = 'WASO Systems';
    pptx.title = title;

    // Slide 1: Title Slide (Dark Cyber Theme)
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: '0A192F' }; // WASO Theme Dark

    // Decorative Line Accent
    titleSlide.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 1.2,
      w: 0.15,
      h: 4.8,
      fill: { color: '00B4D8' },
    });

    titleSlide.addText('WASO AI PRESENTATION', {
      x: 1.2,
      y: 1.5,
      w: 10.5,
      h: 0.6,
      fontSize: 32,
      bold: true,
      color: '00B4D8',
      fontFace: 'Arial',
    });

    titleSlide.addText(title, {
      x: 1.2,
      y: 2.3,
      w: 10.5,
      h: 1.8,
      fontSize: 22,
      color: 'FFFFFF',
      fontFace: 'Calibri',
    });

    titleSlide.addText('Generated by WASO • Polyglot Virtual Intelligence Created by Wasin', {
      x: 1.2,
      y: 5.2,
      w: 10.5,
      h: 0.5,
      fontSize: 14,
      color: '94A3B8',
      fontFace: 'Calibri',
    });

    // Parse Content into Slides based on Headers (##) or Paragraph Blocks
    const sections = content.split(/(?=\n#{1,3}\s)/g).filter(s => s.trim().length > 0);

    if (sections.length === 0) {
      sections.push(content);
    }

    sections.forEach((sec, idx) => {
      const slide = pptx.addSlide();
      slide.background = { color: '0F172A' };

      // Header Bar
      slide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.9,
        fill: { color: '1E293B' },
      });

      // Extract Section Title
      const lines = sec.trim().split('\n');
      let slideTitle = `Topic ${idx + 1}`;
      let bodyLines: string[] = [];

      if (lines[0].startsWith('#')) {
        slideTitle = lines[0].replace(/^#+\s*/, '');
        bodyLines = lines.slice(1);
      } else {
        bodyLines = lines;
      }

      slide.addText(slideTitle.slice(0, 60), {
        x: 0.5,
        y: 0.15,
        w: 12.0,
        h: 0.6,
        fontSize: 20,
        bold: true,
        color: '00B4D8',
        fontFace: 'Arial',
      });

      const bodyText = bodyLines.join('\n').trim();

      // If slide contains code snippet
      if (bodyText.includes('```')) {
        const codeMatch = bodyText.match(/```(\w*)\n([\s\S]*?)```/);
        const codeContent = codeMatch ? codeMatch[2] : bodyText;

        slide.addShape(pptx.ShapeType.rect, {
          x: 0.5,
          y: 1.2,
          w: 12.33,
          h: 5.4,
          fill: { color: '090D16' },
          line: { color: '00B4D8', width: 1 },
        });

        slide.addText(codeContent.slice(0, 1500), {
          x: 0.7,
          y: 1.4,
          w: 11.9,
          h: 5.0,
          fontSize: 12,
          color: 'E2E8F0',
          fontFace: 'Courier New',
        });
      } else {
        // Bullet points / Text Body
        const bullets = bodyText
          .split('\n')
          .filter(l => l.trim().length > 0)
          .slice(0, 8);

        const items = bullets.map(b => ({
          text: b.replace(/^[-*•]\s*/, ''),
          options: { fontSize: 16, color: 'E2E8F0', bullet: true, spaceAfter: 8 },
        }));

        if (items.length > 0) {
          slide.addText(items as any, {
            x: 0.6,
            y: 1.3,
            w: 12.0,
            h: 5.2,
            fontFace: 'Calibri',
          });
        }
      }

      // Footer
      slide.addText(`WASO Presentation • Slide ${idx + 2}`, {
        x: 0.5,
        y: 6.8,
        w: 12.0,
        h: 0.4,
        fontSize: 10,
        color: '64748B',
      });
    });

    const filename = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 30)}_WASO.pptx`;
    pptx.writeFile({ fileName: filename });
  } catch (err) {
    console.error('Failed to export PPTX:', err);
    alert('PPTX Export failed. Please try again.');
  }
}
